# Generated by Django 3.0.2 on 2020-01-29 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.BigIntegerField()),
                ('longitude', models.BigIntegerField()),
                ('heartrate', models.IntegerField()),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='AzadiApp.Watch')),
            ],
        ),
    ]
