# Generated by Django 3.0.3 on 2020-02-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='track_location',
            field=models.BooleanField(default=False),
        ),
    ]
