# Generated by Django 3.0.2 on 2020-01-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AzadiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='watch', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
