# Generated by Django 3.0.11 on 2020-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0002_watch_track_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='excercise_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='watch',
            name='type_of_attack',
            field=models.CharField(choices=[('p', 'simulated attack'), ('f', 'fall detected'), ('h', 'heartrate spike'), ('o', 'Outside Range')], max_length=2, null=True),
        ),
    ]
