# Generated by Django 3.0.2 on 2020-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0002_watch_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='location_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='watch',
            name='last_location',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='heartrate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='latitude',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='longitude',
            field=models.BigIntegerField(null=True),
        ),
    ]
