# Generated by Django 3.0.2 on 2020-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0004_watch_full_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='under_attack',
            field=models.BooleanField(default=False),
        ),
    ]
