# Generated by Django 3.0.2 on 2020-01-29 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AzadiApp', '0005_watch_under_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='trusted_users',
            field=models.ManyToManyField(related_name='watches', to=settings.AUTH_USER_MODEL),
        ),
    ]
