# Generated by Django 3.0.3 on 2020-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0006_watch_trusted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='type_of_attack',
            field=models.CharField(choices=[('p', 'physical attack'), ('f', 'fall'), ('h', 'heart attack')], default='p', max_length=2),
            preserve_default=False,
        ),
    ]
