# Generated by Django 3.0.3 on 2020-02-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0007_watch_type_of_attack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='type_of_attack',
            field=models.CharField(choices=[('p', 'physical attack'), ('f', 'fall'), ('h', 'heart attack')], max_length=2, null=True),
        ),
    ]
