# Generated by Django 3.0.3 on 2020-02-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0008_auto_20200206_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='under_attack',
        ),
    ]
