# Generated by Django 3.0.3 on 2020-02-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AzadiApp', '0009_remove_watch_under_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='home_latitude',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='watch',
            name='home_longitude',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='watch',
            name='type_of_attack',
            field=models.CharField(choices=[('p', 'physical attack'), ('f', 'fall detected'), ('h', 'heart attack'), ('o', 'Outside Range')], max_length=2, null=True),
        ),
    ]
